# Generated by Django 5.0.4 on 2024-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
