# Generated by Django 5.0.4 on 2024-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='isDeleted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
